[workspace]
members = ["eclipse_framebuffer","kernel","luminal"]
resolver = "2"

[workspace.dependencies]
x86_64 = "0.15.2"
limine = "0.5.0"
uart_16550 = "0.4.0"
luminal_rt = { path = "./luminal", default-features = false }
eclipse_framebuffer ={ path = "./eclipse_framebuffer" }